### ISSUE TITLE
Filter & Sort

### ISSUE THREAD

**Issue by BruceWheaton** [MrHertal/react-admin-amplify#52]
Can I sort or filter post receiving data i.e. without using custom queryFields?

On filter - how can I use wildcards? 

On sort, it seems that we can't sort on the primary key, only the secondary key. Is that right? Is that an Appsync limitation or just the way sorts currently work?

**Comment by MrHertal** [comment]
Hi,

Filtering and sorting is pretty limited because of AppSync/DynamoDB.

If you want more info, check these sections of the README:

https://github.com/MrHertal/react-admin-amplify#filter
https://github.com/MrHertal/react-admin-amplify#sorting

For more details there is also [the Amplify documentation](https://docs.amplify.aws/cli/graphql-transformer/key).
